name: Semantic Release

on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: 0 16 * * 0 # Weekly pre-releases at midnight Monday GMT+8
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v4
        name: Setup bun cache
        with:
          path: ~/.bun/install/cache
          key: "${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}"
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Project Dependencies
        run: bun install

      - name: Run semantic-release
        run: HUSKY=0 bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
